// Tailwind configuration mirroring the inline tailwind.config from
// index.html. Used by the offline-build script to pre-compile a static
// CSS bundle, so the offline HTML doesn't need cdn.tailwindcss.com.
//
// Keep this in sync with the `tailwind.config = {...}` block inside
// <script id="tailwind-config"> in index.html.

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './app.js', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#5c4300',
        'tertiary': '#f9bd22',
        'tertiary-container': '#c79500',
        'on-primary': '#381385',
        'surface': '#151219',
        'surface-container': '#221e26',
        'primary-fixed': '#e8ddff',
        'on-primary-container': '#3c1989',
        'surface-container-lowest': '#100d14',
        'background': '#151219',
        'error-container': '#93000a',
        'surface-container-highest': '#37333b',
        'on-secondary-container': '#00452e',
        'on-surface-variant': '#cac4d4',
        'on-tertiary-container': '#453100',
        'primary-fixed-dim': '#cebdff',
        'surface-variant': '#37333b',
        'surface-dim': '#151219',
        'on-error': '#690005',
        'surface-tint': '#cebdff',
        'secondary-fixed': '#68fcbf',
        'on-primary-fixed': '#21005e',
        'secondary-fixed-dim': '#45dfa4',
        'primary-container': '#a78bfa',
        'primary': '#cebdff',
        'primary-hover': '#e8ddff',
        'outline': '#948e9d',
        'inverse-surface': '#e8e0eb',
        'tertiary-fixed-dim': '#f9bd22',
        'on-tertiary-fixed': '#261a00',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#4f319c',
        'surface-container-high': '#2c2830',
        'on-secondary-fixed-variant': '#005137',
        'surface-container-low': '#1e1a22',
        'secondary-container': '#00bd85',
        'outline-variant': '#494552',
        'on-surface': '#e8e0eb',
        'on-background': '#e8e0eb',
        'inverse-primary': '#674bb5',
        'on-secondary-fixed': '#002114',
        'surface-bright': '#3c3840',
        'inverse-on-surface': '#332f37',
        'secondary': '#45dfa4',
        'on-secondary': '#003825',
        'error': '#ffb4ab',
        'tertiary-fixed': '#ffdf9f',
        'on-tertiary': '#402d00',
        'surface-hover': 'rgba(44, 40, 50, 0.6)',
        'border-thin': 'rgba(206, 189, 255, 0.2)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '32px',
        'container-max': '1440px',
        'stack-sm': '8px',
        'margin-desktop': '40px',
        'gutter': '24px',
        'unit': '8px',
        'margin-mobile': '16px',
        'sidebar-width': '256px',
        'card-gap': '24px',
        'container-padding': '40px',
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'body-base': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
        'data-tabular': ['Hanken Grotesk', 'Assistant', 'sans-serif'],
      },
      fontSize: {
        'body-lg':           ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-lg':        ['48px', { lineHeight: '1.1', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg-mobile':['28px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md':           ['16px', { lineHeight: '1.5', letterSpacing: '0',      fontWeight: '400' }],
        'headline-md':       ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg':       ['32px', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-sm':          ['12px', { lineHeight: '1',   letterSpacing: '0.1em',  fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
